package controller;
// Generated 23/11/2014 10:45:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Advertisement generated by hbm2java
 */
public class Advertisement  implements java.io.Serializable {


     private Integer advCod;
     private Category category;
     private Customer customer;
     private String title;
     private String description;
     private Float value;
     private String site;
     private String email;
     private String phone;
     private Boolean hideAdvCod;
     private Integer counter;
     private Set hidelogs = new HashSet(0);
     private Set images = new HashSet(0);

    public Advertisement() {
    }

    public Advertisement(Category category, Customer customer, String title, String description, Float value, String site, String email, String phone, Boolean hideAdvCod, Integer counter, Set hidelogs, Set images) {
       this.category = category;
       this.customer = customer;
       this.title = title;
       this.description = description;
       this.value = value;
       this.site = site;
       this.email = email;
       this.phone = phone;
       this.hideAdvCod = hideAdvCod;
       this.counter = counter;
       this.hidelogs = hidelogs;
       this.images = images;
    }
   
    public Integer getAdvCod() {
        return this.advCod;
    }
    
    public void setAdvCod(Integer advCod) {
        this.advCod = advCod;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Float getValue() {
        return this.value;
    }
    
    public void setValue(Float value) {
        this.value = value;
    }
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Boolean getHideAdvCod() {
        return this.hideAdvCod;
    }
    
    public void setHideAdvCod(Boolean hideAdvCod) {
        this.hideAdvCod = hideAdvCod;
    }
    public Integer getCounter() {
        return this.counter;
    }
    
    public void setCounter(Integer counter) {
        this.counter = counter;
    }
    public Set getHidelogs() {
        return this.hidelogs;
    }
    
    public void setHidelogs(Set hidelogs) {
        this.hidelogs = hidelogs;
    }
    public Set getImages() {
        return this.images;
    }
    
    public void setImages(Set images) {
        this.images = images;
    }




}


