package controller;
// Generated 23/11/2014 10:45:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer catgCod;
     private String title;
     private Set advertisements = new HashSet(0);

    public Category() {
    }

    public Category(String title, Set advertisements) {
       this.title = title;
       this.advertisements = advertisements;
    }
   
    public Integer getCatgCod() {
        return this.catgCod;
    }
    
    public void setCatgCod(Integer catgCod) {
        this.catgCod = catgCod;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getAdvertisements() {
        return this.advertisements;
    }
    
    public void setAdvertisements(Set advertisements) {
        this.advertisements = advertisements;
    }




}


