package controller;
// Generated 23/11/2014 10:45:47 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Hidelog generated by hbm2java
 */
public class Hidelog  implements java.io.Serializable {


     private Integer hlogCod;
     private Moderator moderator;
     private Advertisement advertisement;
     private String descricao;
     private Date dateLog;

    public Hidelog() {
    }

    public Hidelog(Moderator moderator, Advertisement advertisement, String descricao, Date dateLog) {
       this.moderator = moderator;
       this.advertisement = advertisement;
       this.descricao = descricao;
       this.dateLog = dateLog;
    }
   
    public Integer getHlogCod() {
        return this.hlogCod;
    }
    
    public void setHlogCod(Integer hlogCod) {
        this.hlogCod = hlogCod;
    }
    public Moderator getModerator() {
        return this.moderator;
    }
    
    public void setModerator(Moderator moderator) {
        this.moderator = moderator;
    }
    public Advertisement getAdvertisement() {
        return this.advertisement;
    }
    
    public void setAdvertisement(Advertisement advertisement) {
        this.advertisement = advertisement;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDateLog() {
        return this.dateLog;
    }
    
    public void setDateLog(Date dateLog) {
        this.dateLog = dateLog;
    }




}


