package controller;
// Generated 23/11/2014 10:45:47 by Hibernate Tools 3.6.0



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private Integer imgCod;
     private Advertisement advertisement;
     private String imgTitle;
     private String imgAddress;

    public Image() {
    }

    public Image(Advertisement advertisement, String imgTitle, String imgAddress) {
       this.advertisement = advertisement;
       this.imgTitle = imgTitle;
       this.imgAddress = imgAddress;
    }
   
    public Integer getImgCod() {
        return this.imgCod;
    }
    
    public void setImgCod(Integer imgCod) {
        this.imgCod = imgCod;
    }
    public Advertisement getAdvertisement() {
        return this.advertisement;
    }
    
    public void setAdvertisement(Advertisement advertisement) {
        this.advertisement = advertisement;
    }
    public String getImgTitle() {
        return this.imgTitle;
    }
    
    public void setImgTitle(String imgTitle) {
        this.imgTitle = imgTitle;
    }
    public String getImgAddress() {
        return this.imgAddress;
    }
    
    public void setImgAddress(String imgAddress) {
        this.imgAddress = imgAddress;
    }




}


