package controller;
// Generated 23/11/2014 10:45:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userCod;
     private String login;
     private String password;
     private String email;
     private Integer level;
     private Set customers = new HashSet(0);
     private Set moderators = new HashSet(0);

    public User() {
    }

    public User(String login, String password, String email, Integer level, Set customers, Set moderators) {
       this.login = login;
       this.password = password;
       this.email = email;
       this.level = level;
       this.customers = customers;
       this.moderators = moderators;
    }
   
    public Integer getUserCod() {
        return this.userCod;
    }
    
    public void setUserCod(Integer userCod) {
        this.userCod = userCod;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }
    public Set getModerators() {
        return this.moderators;
    }
    
    public void setModerators(Set moderators) {
        this.moderators = moderators;
    }




}


